%%----------------------------------------------
%  DETAILS FOR TB WGS CLINICAL REPORT TEMPLATE
%%---------------------------------------------
% Version : Sweave 1.0 
% Latex template is also available on Overleaf: TBR
%
% Report template is not provided for diagnostic purposes.
% Report template's design decision outline in the following publication: TBR
% Maintained by: Anamaria Crisan (acrisan@cs.ubc.ca)


\documentclass{article}
%%------------------------------------------
%  THIRD PARTY PACKAGES
%%------------------------------------------
% Note: make sure these packages are install on your machine before using
\usepackage[letterpaper, margin=0.75in,headheight=77pt,top=3.5cm]{geometry}
\usepackage{Sweave} %this needs to go before "fontspec" in order to get Lato font to work
\usepackage{fancyhdr}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage[table]{xcolor}
\usepackage{tabu}
\usepackage{collcell}
\usepackage{multirow}
\usepackage[skins]{tcolorbox}
\usepackage{fontspec}
  \setmainfont{Lato}

%--------- NEW COMMANDS
\newcolumntype{U}{>{\collectcell\MakeUppercase}l<{\endcollectcell}}

\tcbuselibrary{listings,breakable}

%bounding box for report sections
\newtcolorbox{reportSection}[2][]{%
  attach boxed title to top left
  			   = {xshift=10pt, yshift=-8pt},
  colback      = white!5!white,
  colframe     = white!75!black,
  fonttitle    = \bfseries,
  colbacktitle = white,
  title        = \textbf{\large{#2}},
  coltitle	   = black,
  arc = 0mm,
  opacityframe = 0.5,
  boxrule=1pt,
  boxed title style={%
    sharp corners, 
    rounded corners=northwest, 
    colback=white, 
    boxrule=0pt,
    titlerule=0mm},
  enhanced,
}



%--------------------------------------------
% Creating Header & Footer with Text, Logo and Page Number
%-------------------------------------------

%-------------- HEADER CONTENT ------------
\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{0pt}

% HEADER TEXT
\lhead{\Large{\textbf{MYCOBACTERIUM TUBERCULOSIS WHOLE\\ GENOME SEQUENCING REPORT}} \\ \normalsize{NOT FOR DIAGNOSTIC USE}}
\chead{}
\rhead{PICTURE HERE}

%-------------- FOOTER CONTENT ------------
\rfoot{This is a test}

%%------------------------------------------
%  DOCUMENT CONTENT
%%------------------------------------------

\begin{document}
\SweaveOpts{concordance=TRUE}
%\SweaveOpts{concordance=TRUE}

\tabulinesep=5pt
\noindent 
\taburulecolor{lightgray}
\noindent \begin{tabu} to \textwidth {|XU||XU|}
\hline

% Making the table manually
% you may wonder: where does magical pInfo variable come from, the answer is "runReportExample.R", the variable
% get's automatically passed to the text document by the Sweave commands in the "makeReport" function.

<<patientInfoTab, results=tex, echo=FALSE>>=
cat("Patient Name  &",paste(pInfo$FName,pInfo$LName,sep=" "), "& Patient ID  &",pInfo$ID,"\\\\ \\hline ")
cat("Birth Date &", pInfo$DOB, "& Location &", pInfo$Location,"\\\\ \\hline ")
cat("Sample Type &",pInfo$sampType,"& Sample Date &", pInfo$sampDate, "\\\\ \\hline ")
cat("Reporting Lab &", pInfo$reportLab,"& Report Date &", pInfo$reportDate,"\\\\ \\hline ")
@

\end{tabu}
\vspace{5mm}

%---------------------------------------------------------
%  SECTION 1 : SUMMARY OF REPORT CONTENT
%---------------------------------------------------------

\begin{reportSection}{Summary}
\vspace{1mm}

% This is a custom paragraph that needs to be automatically generated.
<<sec1:summaryText,echo=FALSE,results=tex>>=
cat(pInfo$summary)
@

\end{reportSection}
\vspace{5mm}

%---------------------------------------------------------
%  SECTION 2 : SUMMARY OF SPECIATION RESULTS
%---------------------------------------------------------

\begin{reportSection}{Organism}
\vspace{1mm}

The specimen was positive for \textbf{Mycobacterium tuberculosis}
\end{reportSection}
\vspace{5mm}

%---------------------------------------------------------
%  SECTION 3 : SUMMARY OF SDRUG SUSCEPTIBILITY RESULTS
%---------------------------------------------------------

\begin{reportSection}{Drug Susceptibility}

%--------- Text for drug susceptibility and also the summary tick boxes
\vspace{1mm}
\tabulinesep=2pt
\noindent 
\taburulecolor{lightgray}
\noindent \begin{tabu} to \textwidth {X[1.1,l]X}
\multirow{4}{*}{\parbox{7.5cm}{\footnotesize{Drug susceptibility is predicted by the detection of known \textit{M. tuberculosis} drug resistance conferring genetic mutations}}} & $\square$ No drug resistance predicted \\
& $\square$ Mono-resistance predicted \\
&  \cellcolor[HTML]{EFEFEF} $\text{\rlap{$\checkmark$}}\square$ Multi-drug resistance predicted \\
& $\square$ Extensive drug resistance predicted \\
\end{tabu}

\vspace{3mm} %% Add a Bit of space between the entities

%--------- Summary of drug susceptibility - table
\tabulinesep=5pt
\noindent 
\taburulecolor{lightgray}
\noindent \begin{tabu} to \textwidth {X[0.5,l]X[0.5,l]XX[2,l]}
%--------------- v ADD YOUR TABLE CONTENTS BELOW v---------------------
\hline
Drug class                    & Prediction                                          & Drug                              & 
Resistance Gene \scriptsize{(Amino Acid Mutation)}          \\
\cline{1-4}
                              &                                                     & Ethambutol                        & No resistance mutation detected      \\
                              & \multirow{-2}{*}{Sensitive}                         & Pyrazinimide                      & No resistance mutation detected      \\
                              & \cellcolor[HTML]{EFEFEF}                            & \cellcolor[HTML]{EFEFEF}Isoniazid & \cellcolor[HTML]{EFEFEF}katG (S315T) \\
\multirow{-4}{*}{First Line}  & \multirow{-2}{*}{\cellcolor[HTML]{EFEFEF}Resistant} & \cellcolor[HTML]{EFEFEF}Rifampin  & \cellcolor[HTML]{EFEFEF}rpoB (S531L) \\
\cline{1-4}
                              &                                                     & Streptomycin                      & No resistance mutation detected      \\
                              &                                                     & Ciprofloxacin                     & No resistance mutation detected      \\
                              &                                                     & Ofloxacin                         & No resistance mutation detected      \\
                              &                                                     & Moxifloacin                       & No resistance mutation detected      \\
                              &                                                     & Amikacin                          & No resistance mutation detected      \\
                              &                                                     & Kanamycin                         & No resistance mutation detected      \\
\multirow{-7}{*}{Second Line} & \multirow{-7}{*}{Sensitive}                         & Capreomycin                       & No resistance mutation detected	\\
\cline{1-4}
%--------------- ^ ADD YOUR TABLE CONTENTS ABOVE ^ ---------------------
\end{tabu}
\end{reportSection}


%---------------------------------------------------------
%  SECTION 4 : CLUSTER DETECTION RESULTS
%---------------------------------------------------------
\pagebreak

\begin{reportSection}{Cluster Detection}
This is some text that will support stuff if the cluster detection.
\end{reportSection}

\end{document}